package com.members.model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;


import static connection.JDBCConnection.USERNAME;
import static connection.JDBCConnection.PASSWORD;
import static connection.JDBCConnection.URL;
import static connection.JDBCConnection.DRIVER;

public class MembersJDBCDAO implements MembersDAO_interface {

	private static final String INSERT_STMT = 
			"INSERT INTO members(account,password,name,address,phone,rank_id,e_wallet_amount,e_wallet_password,bonus_amount,status) "
			+ "values(?,?,?,?,?,?,?,?,?,?);";
	private static final String UPDATE = 
			"UPDATE members set account=?,password=?,name=?,address=?,phone=?,rank_id=?,e_wallet_amount=?,e_wallet_password=?,bonus_amount=?,status=? "
			+ "where member_id = ?;";
	private static final String DELETE = 
			"DELETE FROM members where member_id = ?";
	private static final String GET_ALL_STMT = 
			"SELECT member_id,account,password,name,address,phone,rank_id,e_wallet_amount,e_wallet_password,bonus_amount,status,create_time FROM members order by member_id";
	private static final String GET_ONE_STMT = 
			"SELECT member_id,account,password,name,address,phone,rank_id,e_wallet_amount,e_wallet_password,bonus_amount,status,create_time FROM members where member_id = ?";

	@Override
	public void insert(MembersVO memberVO) {
		String columns[] = { "member_id" }; // autoGeneratedKeys
		try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);
				PreparedStatement ps = connection.prepareStatement(INSERT_STMT, columns)) {

			ps.setString(1, memberVO.getAccount()); // �|���b�� string
			ps.setString(2, memberVO.getPassword()); // �|���K�X string
			ps.setString(3, memberVO.getName()); // �|���W�� string
			ps.setString(4, memberVO.getAddress()); // �|���a�} string
			ps.setString(5, memberVO.getPhone()); // �|���q�� string
			ps.setInt(6, memberVO.getRank_id()); // �|������ int
			ps.setInt(7, memberVO.getE_wallet_amount()); // ���]�l�B int
			ps.setString(8, memberVO.getE_wallet_password()); // ���]�K�X string
			ps.setInt(9, memberVO.getBonus_amount()); // ���Q�b�� int
			ps.setInt(10, memberVO.getStatus()); // �b�᪬�A int
			int rowCount = ps.executeUpdate();

			// DQL ��ܥثe�s�W��ĴX�����
			ResultSet rs = ps.getGeneratedKeys(); // �� getGeneratedKeys ���o�۰ʽs��
			if (rs.next()) {
				int members_id = rs.getInt(1);
				System.out.println(rowCount + " row inserted; Employee ID: " + members_id);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}

	}

	@Override
	public void update(MembersVO memberVO) {
		try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);
				PreparedStatement ps = connection.prepareStatement(UPDATE)) {

			ps.setString(1, memberVO.getAccount()); // �|���b�� string
			ps.setString(2, memberVO.getPassword()); // �|���K�X string
			ps.setString(3, memberVO.getName()); // �|���W�� string
			ps.setString(4, memberVO.getAddress()); // �|���a�} string
			ps.setString(5, memberVO.getPhone()); // �|���q�� string
			ps.setInt(6, memberVO.getRank_id()); // �|������ int
			ps.setInt(7, memberVO.getE_wallet_amount()); // ���]�l�B int
			ps.setString(8, memberVO.getE_wallet_password()); // ���]�K�X string
			ps.setInt(9, memberVO.getBonus_amount()); // ���Q�b�� int
			ps.setInt(10, memberVO.getStatus()); // �b�᪬�A int
			ps.setInt(11, memberVO.getMember_id());
			int rowCount = ps.executeUpdate();
			System.out.println(rowCount + "row(s) updated!");
		} catch (SQLException e) {
			e.printStackTrace();
		}

	}

	@Override
	public void delete(Integer member_id) {
		try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);
				PreparedStatement ps = connection.prepareStatement(DELETE)) {
			ps.setInt(1, member_id);
			int rowCount = ps.executeUpdate();
			System.out.println(rowCount + "row(s) deleted!");
		} catch (SQLException e) {
			e.printStackTrace();
		}

	}

	@Override
	public MembersVO findByPrimaryKey(Integer member_id) {
		/*
		 * 	new �@�� MembersVO �Ӹˬd�ߪ����G
		 * */
		MembersVO membersVO = new MembersVO();
		try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);
				PreparedStatement ps = connection.prepareStatement(GET_ONE_STMT)) {
			ps.setInt(1, member_id);
			/*
		 		��Statement�����AResultSet�]�|�۰������A �i�H���ݭn�NResultSet�ŧi�m�J try with
		    */
			ResultSet rs = ps.executeQuery();
			while (rs.next()) {
				membersVO.setMember_id(rs.getInt("member_id"));
				membersVO.setAccount(rs.getString("account"));
				membersVO.setPassword(rs.getString("password"));
				membersVO.setName(rs.getString("name"));
				membersVO.setAddress(rs.getString("address"));
				membersVO.setPhone(rs.getString("phone"));
				membersVO.setRank_id(rs.getInt("rank_id"));
				membersVO.setE_wallet_amount(rs.getInt("e_wallet_amount"));
				membersVO.setE_wallet_password(rs.getString("e_wallet_password"));
				membersVO.setBonus_amount(rs.getInt("bonus_amount"));
				membersVO.setStatus(rs.getInt("status"));
				membersVO.setCreate_time(rs.getTimestamp("create_time"));
			}
		} catch (SQLException e) {
			throw new RuntimeException("A database error occured. "
					+ e.getMessage());
		}
		return membersVO;
	}

	@Override
	public List<MembersVO> getAll() {
		
		List<MembersVO> list = new ArrayList<MembersVO>();
		try (Connection connection = DriverManager.getConnection(URL, USERNAME, PASSWORD);
				PreparedStatement ps = connection.prepareStatement(GET_ALL_STMT)) {
			ResultSet rs = ps.executeQuery();
			while (rs.next()) {
				MembersVO membersVO = new MembersVO();
				membersVO.setMember_id(rs.getInt("member_id"));
				membersVO.setAccount(rs.getString("account"));
				membersVO.setPassword(rs.getString("password"));
				membersVO.setName(rs.getString("name"));
				membersVO.setAddress(rs.getString("address"));
				membersVO.setPhone(rs.getString("phone"));
				membersVO.setRank_id(rs.getInt("rank_id"));
				membersVO.setE_wallet_amount(rs.getInt("e_wallet_amount"));
				membersVO.setE_wallet_password(rs.getString("e_wallet_password"));
				membersVO.setBonus_amount(rs.getInt("bonus_amount"));
				membersVO.setStatus(rs.getInt("status"));
				membersVO.setCreate_time(rs.getTimestamp("create_time"));
				list.add(membersVO);
			}
		} catch (SQLException e) {
			throw new RuntimeException("A database error occured. "
					+ e.getMessage());
		}
		return list;
	}

	public static void main(String[] args) {
		/*
		 * JDBC4.0 ���e���J JDBC Driver ���覡�A�{�b�i�H�ٲ�
		 */
		try {
			Class.forName(DRIVER);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
			return;
		}

		/*
		 * �إ� JDBC �������
		 */
		MembersJDBCDAO dao = new MembersJDBCDAO();

		/*
		 * �إ� MembersVO1 �������A�éI�s dao.insert() ��k
		 */
		MembersVO membersVO1 = new MembersVO();

//		membersVO1.setMember_id( �۰ʽs�� int );
		membersVO1.setAccount("css@pet.com"); // �|���b�� string
		membersVO1.setPassword("!QAZ2wsx"); // �|���K�X string
		membersVO1.setName("�N��"); // �|���W�� string
		membersVO1.setAddress("�x���j�����i�c"); // �|���a�} string
		membersVO1.setPhone("0988462556"); // �|���q�� string
		membersVO1.setRank_id(4); // �|������ int
		membersVO1.setE_wallet_amount(645); // ���]�l�B int
		membersVO1.setE_wallet_password("449135"); // ���]�K�X string
		membersVO1.setBonus_amount(20); // ���Q�b�� int
		membersVO1.setStatus(1); // �b�᪬�A int
//		membersVO1.setCreate_time( �b��Ыخɶ� );
		dao.insert(membersVO1);

		/*
		 * �إ� MembersVO2 �������A�éI�s dao.update() ��k
		 */
		MembersVO membersVO2 = new MembersVO();

		membersVO2.setMember_id( 13 );
		membersVO2.setAccount("css3@pet.com"); // �|���b�� string
		membersVO2.setPassword("!QAZ2wsx"); // �|���K�X string
		membersVO2.setName("�f��"); // �|���W�� string
		membersVO2.setAddress("�x�_���`�Ω�"); // �|���a�} string
		membersVO2.setPhone("0988462556"); // �|���q�� string
		membersVO2.setRank_id(4); // �|������ int
		membersVO2.setE_wallet_amount(505); // ���]�l�B int
		membersVO2.setE_wallet_password("666888"); // ���]�K�X string
		membersVO2.setBonus_amount(50); // ���Q�b�� int
		membersVO2.setStatus(1); // �b�᪬�A int
//		membersVO1.setCreate_time( �b��Ыخɶ� );
		dao.update(membersVO2);

		
		// �R��
		dao.delete(13);
		
		
		// �d�ߤ@�����
		MembersVO membersVO3 = dao.findByPrimaryKey(1);
		System.out.println("�|���s���G"+membersVO3.getMember_id());
		System.out.println("�|���b���G"+membersVO3.getAccount()); 
		System.out.println("�|���K�X�G"+membersVO3.getPassword()); 
		System.out.println("�|���W�١G"+membersVO3.getName()); 
		System.out.println("�|���a�}�G"+membersVO3.getAddress()); 
		System.out.println("�|���q�ܡG"+membersVO3.getPhone()); 
		System.out.println("�|�����šG"+membersVO3.getRank_id()); 
		System.out.println("���]�l�B�G"+membersVO3.getE_wallet_amount()); 
		System.out.println("���]�K�X�G"+membersVO3.getE_wallet_password()); 
		System.out.println("���Q�b��G"+membersVO3.getBonus_amount()); 
		System.out.println("�b�᪬�A�G"+membersVO3.getStatus()); 
		System.out.println("�b��Ыخɶ��G"+membersVO3.getCreate_time());

		// �d�ߦh�����
		List<MembersVO> list = dao.getAll();
		for(MembersVO aMem:list) {
			System.out.println("�|���s���G"+aMem.getMember_id());
			System.out.println("�|���b���G"+aMem.getAccount()); 
			System.out.println("�|���K�X�G"+aMem.getPassword()); 
			System.out.println("�|���W�١G"+aMem.getName()); 
			System.out.println("�|���a�}�G"+aMem.getAddress()); 
			System.out.println("�|���q�ܡG"+aMem.getPhone()); 
			System.out.println("�|�����šG"+aMem.getRank_id()); 
			System.out.println("���]�l�B�G"+aMem.getE_wallet_amount()); 
			System.out.println("���]�K�X�G"+aMem.getE_wallet_password()); 
			System.out.println("���Q�b��G"+aMem.getBonus_amount()); 
			System.out.println("�b�᪬�A�G"+aMem.getStatus()); 
			System.out.println("�b��Ыخɶ��G"+aMem.getCreate_time());
		}

	}

}
